x = "Hello World" #str
x = 20 #int
x = 20.5 #float
x = ["apple","banana","cherry"] #list
x = ("apple","banana","cherry") #tuple
x = {name: "taratep", age:21} #dict
x = {"apple","banana","cherry"} #set
x = frozenset({"apple","banana","cherry"}) #frozenset
x = True #bool
x = b"hello" #bytes
